spring.application.name=social_media_api

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/url_shortcut
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# Liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/dbchangelog.xml
spring.liquibase.url=jdbc:postgresql://127.0.0.1:5432/url_shortcut
spring.liquibase.user=postgres
spring.liquibase.password=postgres

socialmedia.openapi.dev-url=http://localhost:8080
socialmedia.openapi.prod-url=https://mydomen.com
springdoc.swagger-ui.tryItOutEnabled=true

jwt.token.secret=easehjkopyJhbGciOiJIUzI1NiJ9eyJzdWIiOiJzdHVkZW50X2pvYjRqIiwiaWF0Ijox
jwt.token.expired=3600000

spring.task.execution.pool.core-size=1
spring.task.execution.pool.max-size=5
spring.task.execution.pool.queue-capacity=10

spring.task.scheduling.pool.size=10